# Generated by Django 5.2.8 on 2025-11-08 19:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kazamata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=100, unique=True, verbose_name='Név')),
                ('tipus', models.CharField(choices=[('egyszeru', 'Egyszerű találkozás'), ('kis', 'Kis kazamata'), ('nagy', 'Nagy kazamata')], max_length=10, verbose_name='Típus')),
            ],
            options={
                'verbose_name': 'Kazamata',
                'verbose_name_plural': 'Kazamaták',
            },
        ),
        migrations.CreateModel(
            name='Vezerkartya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=16, unique=True, verbose_name='Név')),
                ('duplazas_tipusa', models.CharField(choices=[('sebzes', 'Sebzés duplázás'), ('eletero', 'Életerő duplázás')], max_length=10, verbose_name='Duplázás típusa')),
            ],
            options={
                'verbose_name': 'Vezérkártya',
                'verbose_name_plural': 'Vezérkártyák',
            },
        ),
        migrations.CreateModel(
            name='Vilagkartya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=16, unique=True, verbose_name='Név')),
                ('sebzes', models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)], verbose_name='Sebzés')),
                ('eletero', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Életerő')),
                ('tipus', models.CharField(choices=[('tuz', 'Tűz'), ('fold', 'Föld'), ('viz', 'Víz'), ('levego', 'Levegő')], max_length=10, verbose_name='Típus')),
            ],
            options={
                'verbose_name': 'Világkártya',
                'verbose_name_plural': 'Világkártyák',
            },
        ),
        migrations.CreateModel(
            name='JatekKornyezet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=100, unique=True, verbose_name='Név')),
                ('letrehozva', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('keszitette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Készítette')),
            ],
            options={
                'verbose_name': 'Játékkörnyezet',
                'verbose_name_plural': 'Játékkörnyezetek',
            },
        ),
        migrations.CreateModel(
            name='Jatek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inditas', models.DateTimeField(auto_now_add=True, verbose_name='Indítás időpontja')),
                ('utolso_aktivitas', models.DateTimeField(auto_now=True, verbose_name='Utolsó aktivitás')),
                ('jatekos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Játékos')),
                ('kornyezet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='damareen.jatekkornyezet', verbose_name='Játékkörnyezet')),
            ],
            options={
                'verbose_name': 'Játék',
                'verbose_name_plural': 'Játékok',
                'unique_together': {('jatekos', 'kornyezet')},
            },
        ),
        migrations.CreateModel(
            name='Jatekoskartya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktualis_sebzes', models.IntegerField(verbose_name='Aktuális sebzés')),
                ('aktualis_eletero', models.IntegerField(verbose_name='Aktuális életerő')),
                ('jatek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gyujtemeny', to='damareen.jatek')),
                ('eredeti_kartya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='damareen.vilagkartya')),
            ],
            options={
                'verbose_name': 'Játékos kártya',
                'verbose_name_plural': 'Játékos kártyák',
                'unique_together': {('jatek', 'eredeti_kartya')},
            },
        ),
        migrations.CreateModel(
            name='Harc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inditas', models.DateTimeField(auto_now_add=True, verbose_name='Indítás')),
                ('befejezve', models.BooleanField(default=False, verbose_name='Befejezve')),
                ('jatekos_gyozott', models.BooleanField(blank=True, null=True, verbose_name='Játékos győzött')),
                ('jatek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harcok', to='damareen.jatek')),
                ('kazamata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='damareen.kazamata')),
            ],
            options={
                'verbose_name': 'Harc',
                'verbose_name_plural': 'Harcok',
                'ordering': ['-inditas'],
            },
        ),
        migrations.CreateModel(
            name='KazamataKartya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorrend', models.IntegerField(verbose_name='Sorrend')),
                ('kazamata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kartyak', to='damareen.kazamata')),
                ('vezer_kartya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='damareen.vezerkartya')),
                ('vilag_kartya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='damareen.vilagkartya')),
            ],
            options={
                'verbose_name': 'Kazamata kártya',
                'verbose_name_plural': 'Kazamata kártyák',
                'ordering': ['sorrend'],
                'unique_together': {('kazamata', 'sorrend')},
            },
        ),
        migrations.CreateModel(
            name='Pakli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letrehozva', models.DateTimeField(auto_now=True, verbose_name='Létrehozva')),
                ('jatek', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pakli', to='damareen.jatek')),
            ],
            options={
                'verbose_name': 'Pakli',
                'verbose_name_plural': 'Paklik',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('player', 'Játékos'), ('master', 'Játékmester')], default='player', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Utközet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorrend', models.IntegerField(verbose_name='Sorrend')),
                ('jatekos_sebzes', models.IntegerField()),
                ('jatekos_eletero', models.IntegerField()),
                ('jatekos_tipus', models.CharField(choices=[('tuz', 'Tűz'), ('fold', 'Föld'), ('viz', 'Víz'), ('levego', 'Levegő')], max_length=10)),
                ('kazamata_sebzes', models.IntegerField()),
                ('kazamata_eletero', models.IntegerField()),
                ('kazamata_tipus', models.CharField(choices=[('tuz', 'Tűz'), ('fold', 'Föld'), ('viz', 'Víz'), ('levego', 'Levegő')], max_length=10)),
                ('jatekos_nyert', models.BooleanField(verbose_name='Játékos nyert')),
                ('gyoztes_ok', models.TextField(verbose_name='Győztes oka')),
                ('harc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utközetek', to='damareen.harc')),
                ('jatekos_kartya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='damareen.jatekoskartya')),
                ('kazamata_kartya_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='damareen.kazamatakartya')),
            ],
            options={
                'verbose_name': 'Ütközet',
                'verbose_name_plural': 'Ütközetek',
                'ordering': ['sorrend'],
            },
        ),
        migrations.AddField(
            model_name='vezerkartya',
            name='eredeti_kartya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='damareen.vilagkartya', verbose_name='Eredeti kártya'),
        ),
        migrations.CreateModel(
            name='PakliKartya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorrend', models.IntegerField(verbose_name='Sorrend')),
                ('kartya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='damareen.jatekoskartya')),
                ('pakli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kartyak', to='damareen.pakli')),
            ],
            options={
                'verbose_name': 'Pakli kártya',
                'verbose_name_plural': 'Pakli kártyák',
                'ordering': ['sorrend'],
                'unique_together': {('pakli', 'kartya'), ('pakli', 'sorrend')},
            },
        ),
        migrations.CreateModel(
            name='GyujtemenyKartya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kornyezet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kezdo_gyujtemeny', to='damareen.jatekkornyezet')),
                ('kartya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='damareen.vilagkartya')),
            ],
            options={
                'verbose_name': 'Gyűjtemény kártya',
                'verbose_name_plural': 'Gyűjtemény kártyák',
                'unique_together': {('kornyezet', 'kartya')},
            },
        ),
    ]
