# Generated by Django 5.2.8 on 2025-11-08 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damareen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=100, unique=True, verbose_name='Név')),
                ('leiras', models.TextField(verbose_name='Leírás')),
                ('ikon', models.CharField(default='🏆', max_length=10, verbose_name='Ikon (emoji)')),
                ('tipus', models.CharField(max_length=50, verbose_name='Típus')),
                ('cel_ertek', models.IntegerField(verbose_name='Cél érték')),
                ('pontok', models.IntegerField(default=10, verbose_name='Pontok')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievementek',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='jelenlegi_sorozat',
            field=models.IntegerField(default=0, verbose_name='Jelenlegi győzelmi sorozat'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='legmagasabb_sorozat',
            field=models.IntegerField(default=0, verbose_name='Leghosszabb győzelmi sorozat'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='osszes_gyozelem',
            field=models.IntegerField(default=0, verbose_name='Összes győzelem'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='osszes_pontszam',
            field=models.IntegerField(default=0, verbose_name='Összes pontszám'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='osszes_vereseg',
            field=models.IntegerField(default=0, verbose_name='Összes vereség'),
        ),
        migrations.CreateModel(
            name='PlayerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('megszerzve', models.DateTimeField(auto_now_add=True, verbose_name='Megszerzve')),
                ('jelenlegi_haladás', models.IntegerField(default=0, verbose_name='Jelenlegi haladás')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='damareen.achievement')),
                ('jatekos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievementek', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Játékos Achievement',
                'verbose_name_plural': 'Játékos Achievementek',
                'unique_together': {('jatekos', 'achievement')},
            },
        ),
    ]
