# Generated by Django 5.2.8 on 2025-11-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damareen', '0002_achievement_userprofile_jelenlegi_sorozat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='harc',
            name='rangsor_frissitve',
            field=models.BooleanField(default=False, verbose_name='Rangsor frissítve'),
        ),
    ]
